FROM argoproj/argocd:v2.0.4

ARG SOPS_VERSION="v3.7.1"
ARG HELM_SECRETS_VERSION="3.8.1"
ARG SOPS_PGP_FP="013D26E064C0758596AE93A986A1183C1DFC20F4"

ENV SOPS_PGP_FP=${SOPS_PGP_FP}

USER root
COPY --chown=argocd:argocd helm-wrapper.sh /usr/local/bin/
RUN apt-get update && \
    apt-get install -y \
    curl \
    gpg && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* && \
    curl -o /usr/local/bin/sops -L https://github.com/mozilla/sops/releases/download/${SOPS_VERSION}/sops-${SOPS_VERSION}.linux && \
    chmod +x /usr/local/bin/sops && \
    cd /usr/local/bin && \
    mv helm _helm && \
    mv helm2 _helm2 && \
    mv helm-wrapper.sh helm && \
    ln helm helm2 && \
    chmod +x helm helm2

# helm secrets plugin should be installed as user argocd or it won't be found
USER 999
COPY --chown=argocd:argocd argocd_demo_gpg.asc /home/argocd/gpg/gpg.asc
RUN /usr/local/bin/_helm plugin install https://github.com/jkroepke/helm-secrets --version ${HELM_SECRETS_VERSION}
ENV HELM_PLUGINS="/home/argocd/.local/share/helm/plugins/"
